### ISSUE TITLE
Pi Supply - Lora Gateway Hat - Support for AU915 Channel Plan

### ISSUE THREAD

**Issue by trick-1** [brocaar/chirpstack-concentratord#19]
Hi Folks, there doesn't seem to be an option to select the AU915 channel plan under the "Pi Supply - Lora Gateway HAT" . Can this please be added?

**Comment by brocaar** [comment]
Sure :) If you would like to create a pull-request for this, then this would be much appreciated.

**Comment by trick-1** [comment]
Sure, any documentation on what files need to be changed/added to, to add a new band plan to a device?

**Comment by trick-1** [comment]
Think I have worked it out will make a pull request shortly after I finish testing

**Comment by trick-1** [comment]
Have updated code, tested and confirmed working. Have submitted pull request for your review.

**Comment by brocaar** [comment]
This has been merged :) Thanks!
