### ISSUE TITLE
wrapper.h:3:10: fatal error: 'libloragw-sx1302/loragw_com.h' file not found

### ISSUE THREAD

**Issue by houzy** [brocaar/chirpstack-concentratord#20]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-concentratord) of this repository and believe that this is not a duplicate.

## What happened?
cargo build return error

## What did you expect?
build this project without any error

## Steps to reproduce this issue

Steps:

1. Install rust
2. git clone https://github.com/brocaar/chirpstack-concentratord.git
3. switch to v3.2.0 tag
4. run cargo build command in the top folder

## Could you share your log output?
   Compiling humantime-serde v1.0.1
   Compiling libloragw-sx1302 v1.0.0 (/home/sensedge/workspace/lora/chirpstack-concentratord/libloragw-sx1302)
   Compiling libloragw-sx1301 v1.0.0 (/home/sensedge/workspace/lora/chirpstack-concentratord/libloragw-sx1301)
   Compiling libloragw-2g4 v1.0.0 (/home/sensedge/workspace/lora/chirpstack-concentratord/libloragw-2g4)
   Compiling chirpstack_api v3.9.7
error: failed to run custom build command for `libloragw-sx1302 v1.0.0 (/home/sensedge/workspace/lora/chirpstack-concentratord/libloragw-sx1302)`

Caused by:
  process didn't exit successfully: `/home/sensedge/workspace/lora/chirpstack-concentratord/target/debug/build/libloragw-sx1302-854eee157eb1870e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=loragw-sx1302
  cargo:rustc-link-lib=tinymt32

  --- stderr
  wrapper.h:3:10: fatal error: 'libloragw-sx1302/loragw_com.h' file not found
  wrapper.h:3:10: fatal error: 'libloragw-sx1302/loragw_com.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', libloragw-sx1302/build.rs:23:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
     1: core::panicking::panic_fmt
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
     2: core::result::unwrap_failed
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
     3: core::result::Result<T,E>::expect
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:997:23
     4: build_script_build::main
               at ./build.rs:14:20
     5: core::ops::function::FnOnce::call_once
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed

```shell

```

## Your Environment
Ubuntu 20.04 x86_64
cargo 1.54.0 (5ae8d74b3 2021-06-22)

| Component           | Version |
| --------------------| ------- |
| Concentratord       |      v3.2.0   |

**Comment by brocaar** [comment]
Concentratord has several external dependencies that you first must setup. The easiest way is to use the provided Docker Compose environment as everything is setup for you: https://www.chirpstack.io/concentratord/community/source/.

**Comment by houzy** [comment]
Thank you.
