### ISSUE TITLE
Add missing RAK245 model configuration

### ISSUE THREAD

**Issue by brocaar** [brocaar/chirpstack-concentratord#6]
Configuration can be found at: https://github.com/RAKWireless/rak_common_for_gateway/tree/dev/lora/rak2245/global_conf

- [x] AS923 pull-request: #4
- [x] AU915
- [x] CN470
- [x] EU433
- [x] EU868
- [x] IN865
- [x] KR920
- [x] RU864
- [x] US915

**Comment by sophiekovalevsky** [comment]
I can help you on this.

**Comment by brocaar** [comment]
@sophiekovalevsky that would be great :) :+1:
